# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18YEOXrRmw4rRz-G20jk1hDKlaHHkiCcm
"""

!pip install pytube
from pytube import YouTube
from pytube import Playlist

SAVE_PATH = "/content/drive/MyDrive/My Songs"  # Change this to your desired download directory

# Playlist URL
playlist_url = "https://youtube.com/playlist?list=PLShuLnMLg5uA0RP65I8D37B45lf3u2qWp&si=lj-xTvK84FqHaSnO"

# Create a Playlist object
playlist = Playlist(playlist_url)

# Iterate through the videos in the playlist and download them as MP4
for i, video_url in enumerate(playlist.video_urls):
    try:
        video = playlist.videos[i]
        title = video.title
        stream = video.streams.filter(only_audio=True).first()
        if stream:
            print(f"Downloading video {i + 1}: {title}")
            stream.download(output_path=SAVE_PATH, filename=(title + ".mp3"))
            print(f"Video {i + 1} downloaded successfully.")
        else:
            print(f"Video {i + 1}: {title} is not available in MP3 format.")
    except Exception as e:
        print(f"Error downloading video {i + 1}: {str(e)}")

# Convert downloaded MP4 files to MP3
for i, video_url in enumerate(playlist.video_urls):
    try:
        video = playlist.videos[i]
        title = video.title
        mp4_path = f"{SAVE_PATH}/{title}.mp4"
        mp3_path = f"{SAVE_PATH}/{title}.mp3"

        if mp4_path and mp3_path:
            print(f"Converting video {i + 1}: {title} to MP3")
            clip = mp.AudioFileClip(mp4_path)
            clip.write_audiofile(mp3_path)
            clip.close()
            print(f"Video {i + 1} converted to MP3 successfully.")
    except Exception as e:
        print(f"Error converting video {i + 1} to MP3: {str(e)}")

print("All videos downloaded and converted to MP3.")